export { default as Home } from "./Home/Home";
export { default as Cart } from "./Cart/Cart";
export { default as About } from "./About/About";
export { default as Contact } from "./Contact/Contact";
export { default as Login } from "./Login/Login";
export { default as Payment } from "./Payment/Payment";
export { default as Products } from "./Products/Products";
export { default as Register } from "./Register/Register";
export { default as Layout } from "./Layout/Layout";
